config/routes.rb
Rails.application.routes.draw do
  get 'payments/new'

  get 'orders/show'


  devise_for :users,
    controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }

  root to: 'pages#home'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :tickets do
    resources :reviews, only: [:index, :new, :create]
    member do
      patch :assign_mentor
    end
  end


  resources :mentor_profils do
    resources :reviews, only: [:show, :edit, :index]
  end

  resources :orders, only: [:show, :create] do
    resources :payments, only: [:new, :create]
  end


  get '/dashboard', to: 'tickets#index', as: 'dashboard'
  get '/tickets/:id/mentor/:mid', to: 'tickets#mentor', as: 'tickets_mentor'
  post '/tickets/:id/close', to: 'tickets#close', as: 'close_ticket'
end

app/views/shared/_bigticketcard.html.erb
<div class="bigcard general-card">
  <div class="row">
    <div class="col-xs-10">
      <h1><%= @ticket.title %></h1>
    </div>
    <div class="col-xs-2">
      <p class="price"><% ticket.price_cents / 100 * ticket.ticket_duration.to_i %></p>
    </div>
  </div>

  <div class="row">
    <div class="col-xs-12 col-md-8">
      <div class="ticket-content"><%= simple_format(@ticket.content) %></div>
    </div>
  </div>
  <div class="row">
    <div class="col-xs-12">
      <div class="skills">
        <p class="secondary-title">Needed skills</p>
        <% ticket.tag_names.each do |skill| %>
          <p class="skill"><%= skill %></p>
        <% end %>
      </div>
    </div>
  </div>

  <div class="row">
    <div class="col-xs-12">
      <div class="informations">
        <div class="bigcard-flag">
          <p class="secondary-title">Languages spoken</p>
          <% ticket.speaking_language.each do |langue| %>
            <span class="flag-icon flag-icon-<%= langue.downcase %>"></span>
          <% end %>
        </div>
        <p class="created-at">Created <%= time_ago_in_words(ticket.created_at) %> ago</p>
      </div>
    </div>
  </div>
</div>

app/views/shared/_card-invoice.html.erb
<div class="card-invoice">
  <div class="card-invoice-title">
    <h2>Resume of your invoice </h2>
  </div>
  <%= form_tag order_payments_path(@order) do %>
    <div class="card-invoice-body">
      <article>
        <p>Number of hours selected : <%= @ticket.ticket_duration %></p>
        <br>
        <p>Price/hour of <%=@ticket.mentor.mentor_profil.full_name %> : <%= @ticket.mentor_profil.minimum_price %> euros</p>
        <br>
        <label class="amount">
          <span>You have a credit of <%= @ticket.ticket_duration  %> hours : <%= humanized_money_with_symbol(@order.amount, delimiter: ' ') %></span>
        </label>
      </article>
    </div>
    <div class="button">
      <div class="btn btn-primary stripe-checkout">
        Credit your account
        <script src="https://checkout.stripe.com/checkout.js" class="stripe-button"
          data-key="<%= Rails.configuration.stripe[:publishable_key] %>"
          data-name="Credited Hours"
          data-email="<%= current_user.email %>"
          data-description="Pay for <%=  @ticket.ticket_duration %> hours"
          data-image="http://lewagon.github.io/ui-components/images/lewagon.png"
          data-amount="<%= @order.amount_cents %>"
          data-currency="<%= @order.amount.currency %>">
        </script>
      </div>
    </div>
  <% end %>
</div>

app/views/shared/_contactcard.html.erb
<div class="contactcard">
  <div class="contactcard-title">
    <h2>Get in touch with <%= mentor.user.first_name %> <%= mentor.user.last_name %> and start working</h2>
  </div>
  <div class="contactcart-contact">
    <p><i class="fa fa-envelope"></i><%= mentor.user.email %></p>
    <p><i class="fa fa-phone"></i><%= mentor.user.phone_number %></p>
  </div>
  <div class="contactcard-tools"></div>
    <a href="https://atom.io/"><%=image_tag'atom-5.svg', :class => "atom" %></a>
    <a href="https://www.skype.com/fr/"><i class="fab fa-skype"></i></a>
    <% if mentor.user.slack_id %>
        <p>
          <%= link_to "https://lewagon-alumni.slack.com/messages/#{mentor.user.slack_id}/", target: "_blank" do %>
            <%= image_tag'slack-1.svg', :class => "slack_img" %>
          <% end %>
        </p>
    <% end %>
  </div>
</div>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= alert %>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<footer class="bg-dark">
  <div class="container">
    <div class="flexbox">
      <div>© 2018 Open a ticket, Inc.</div>


      <ul class="list-inline">
        <li><i class="fab fa-facebook-f text-gray-hover footer-icon-size"></i></li>
        <li><i class="fab fa-twitter text-gray-hover footer-icon-size"></i></li>
        <li><i class="fab fa-github text-gray-hover footer-icon-size"></i></li>
      </ul>

      <div>
        <a class="no-deco footer-font-size text-gray-hover font-weight-light ml-1" href="#">Terms</a>
        <a id="privacy" class="no-deco footer-font-size text-gray-hover font-weight-light ml-1" href="#">Privacy Policy</a>
        <a class="no-deco footer-color footer-font-size text-gray-hover font-weight-light ml-1" href="#">About</a>
      </div>
    </div>
  </div>
</footer>

app/views/shared/_form.html.erb
<!-- Langue::COUNTRIES.values -->
  <div class="container">
    <div class="row">
      <div class="col-xs-6 col-sm-offset-3">
        <div class="form-create">
          <h3 class="center">Create a Ticket</h3>
          <%= simple_form_for ticket do |f| %>
            <%= f.input :title, placeholder:"Title of the ticket" , label: "Title" %>
            <%= f.input :content, placeholder:"
If you are not sure where to start,
here are a few questions to get you started:

What have you done so far, if any?
What do you need help with?
Any attempts?", label: "Description of the ticket" %>
            <%= f.input :tag_names, collection: Gutentag::Tag.all.map(&:name), input_html: { multiple: true },  label: "Needed skills" %>
            <%= f.input :price, placeholder: "Hours rate",  label: "Price/hour maximum" %>
            <%= f.input :ticket_duration, placeholder:"How many hours of help do you need ?" , label: "Number of hours"%>
            <%= f.input :ticket_location, placeholder: "Do you need someone close to you ?" ,label: "Your location (option)"%>
            <%= f.input :speaking_language, collection: LanguageList::ALL_LANGUAGES.select { |language| language.iso_639_1.present? }, label_method: :name, value_method: :iso_639_1, input_html: { multiple: true }, placeholder: "Your native language or Do you accept someone speaking english?",  label: "Languages accepted" %>
            <%= f.input :priority, collection: Ticket::PRIORITIES, prompt: "What is the priority of your mission" , label: "Priority of the mission (option)" %>
            <div class="button">
            <%= f.submit "Your ticket", class: "btn btn-primary" %>
            </div>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/shared/_form2.html.erb
<div class="container">

  <h2>Google Material Design in CSS3<small>Inputs</small></h2>

  <form>

    <div class="group">
      <input type="text" required>
      <span class="highlight"></span>
      <span class="bar"></span>
      <label>Name</label>
    </div>

    <div class="group">
      <input type="text" required>
      <span class="highlight"></span>
      <span class="bar"></span>
      <label>Email</label>
    </div>

  </form>

  <p class="footer">
    a <a href="https://scotch.io/tutorials/css/google-material-design-input-boxes-in-css3" target="_blank">tutorial</a> by <a href="https://scotch.io" target="_blank">scotch.io</a>
  </p>

</div>

app/views/shared/_long-ticket-card.html.erb
<div class="long-ticket-card">
  <div class="primary-informations">
    <h3>
      <%= link_to ticket.title, ticket_path(ticket) %>
      <br><span class="ticket-creation">Created <%= time_ago_in_words(ticket.created_at) %> ago</span>
    </h3>
    <p class="ticket-price">Budget: <%= ticket.price_cents / 100 * ticket.ticket_duration.to_i %> €</p>
  </div>

  <div class="row">
    <div class="col-xs-12 col-sm-8">
      <%= ticket.content %>
    </div>
  </div>

  <div class="data-container">
    <div class="title">Needed skills</div>
    <div class="value">
      <% ticket.tag_names.each do |skill| %>
        <div class="skill">
          <p><%= skill %></p>
        </div>
      <% end %>
    </div>
  </div>

  <div class="data-container">
    <div class="title">Languages accepted</div>
    <div class="value">
      <% ticket.speaking_language.each do |langue| %>
        <span class="flag-icon flag-icon-<%= langue.downcase %>"></span>
      <% end %>
    </div>
  </div>

  <% if ticket.mentor.blank? %>
    <div class="mentors">
      <h3><%= ticket.match_mentors.count %> mentors found</h3>
      <div class="matches">
      <% ticket.match_mentors.each do |mentor| %>
        <%= image_tag mentor.pic_url, class: 'avatar-large' %>
      <% end %>
      </div>
    </div>
   <% else %>
   <div class="mentor">
      <%= image_tag ticket.mentor.pic_url, class: 'avatar-large' %>
      <%= ticket.mentor.mentor_profil.full_name %>
   </div>
  <% end %>


</div>

app/views/shared/_mentorcard.html.erb
<div class="card">
  <div class="informations">
    <img src=<%= mentor.pic_url %> class="avatar-large" alt="avatar">
    <p><%= mentor.first_name %> <%= mentor.last_name %></p>
  </div>

  <div class="card-description">
    <% if mentor.reviews.blank? %>
      <p>No review yet</p>
    <% else %>
      <ul>
        <% mentor.reviews.each do |review| %>
          <li><% review.rating.to_i.times do |i| %>
          <i class="fas fa-star"></i>
        <% end %><% (5 - review.rating.to_i).times do |i| %>
          <i class="far fa-star grey"></i>
        <% end %><%= review.description %> <img src=<%= review.ticket.alumni.pic_url%>  class="avatar-xsmall"></li>
        <% end %>
      </ul>
    <% end %>
  </div>
</div>

app/views/shared/_navbar.html.erb
<nav class="navbar sticky-top bg-white mb-0 flex_box space-around bottom-shadow">
    <div class="flex_box width-90 space-between marginx-auto">

      <div class="logo_part">
        <a id="logo" href="/" text-gray-hover>
          <i class="fas fa-ticket-alt font-30 text-gray"></i>
        </a>
      </div>

      <div class="flex_box space-between">

        <a href="/dashboard" class="btn-open btn-primary text-white ml-2 hidden-xs <%= "hidden" if current_user %> <%= "visible" if !current_user %>">Sign in</a>
          <% if current_user %>
            <div class="flex_box space-between">

              <%= link_to 'Open a ticket', new_ticket_path, class: 'navbar-link' %>
              <%= link_to 'Become a Mentor', new_mentor_profil_path, class: 'navbar-link' %>
              <%= link_to 'My tickets', tickets_path, class: 'navbar-link' %>

              <%= image_tag current_user.pic_url, class: 'avatar ml-2', id: 'user-control' %>

              <div class="open-dropdown hidden">
                <%= link_to "Dashboard", dashboard_path %>
                <%= link_to "Settings", edit_user_registration_path %>
                <%= link_to "Log out", destroy_user_session_path, method: "delete", data: { confirm: "Are you sure you want to log out ?" } %>
              </div>

            </div>
          <% end %>
          <% if !current_user %>
            <span id="user-control"></span>
            <span class="open-dropdown"></span>
          <% end %>
        </div>

      </div>

    </div>
</nav>

app/views/shared/_reviewscard.html.erb
<div class="reviewscard">
  <% if reviews.blank? %>
    <p>No review yet</p>
  <% else %>
    <% reviews.each do |review| %>
      <div class="reviewcard">
        <%= image_tag(review.ticket.alumni.pic_url, class: 'avatar') %>
        <div class="reviewcard-content">
          <div class="reviewcard-rating">
            <% 5.times do |i| %>
              <i class="fas fa-star <%= 'active' if review.rating > i %>"></i>
            <% end %>
          </div>
          <%= review.description %>
        </div>
      </div>
    <% end %>
  <% end %>
</div>

app/views/shared/_sign_up_form.html.erb
<div class="d-flex justify-content-center text-white">

      <div class="ticket">
        <form>
          <div class="row">
            <div class="col">
              <label for="firstname">First name</label>
              <input id="firstname" type="text" class="form-control" placeholder="First name">
            </div>
            <div class="col">
              <label for="lastname">Last name</label>
              <input id="lastname" type="text" class="form-control" placeholder="Last name">
            </div>
          </div>

          <div class="form-group mt-3">
            <label for="email">Email</label>
            <input type="email" class="form-control" id="email" placeholder="thomas@example.com">
          </div>

          <button type="submit" class="btn btn-secondary mt-3 w-100">Send</button>

          </div>
        </form>
      </div>

    </div>

app/views/shared/_square-card-mentor.html.erb
·<div class="square-mentor-card">
  <div data-toggle="modal" data-target="#myModal<%= mentor.id%>">
    <div class="square-mentor-card-title">
      <p><%= mentor.user.batch_wagon %></p>
      <h2><%= mentor.user.first_name %> <%= mentor.user.last_name %></h2>
    </div>

    <div class="square-mentor-card-reviews">
      <% if mentor.user.reviews.blank? %>
        <div>
          <p>No yet reviews </p>
        </div>
      <% else %>
        <div class="square-mentor-card-reviews-stars">
            <% mentor.user.reviews.average(:rating).round().times do |i| %>
              <i class="fas fa-star"></i>
            <% end %>
            <% (5 - mentor.user.reviews.average(:rating).round()).times do |i| %>
              <i class="far fa-star"></i>
              <% end %>
        </div>
      <% end %>
      <p><%= mentor.user.reviews.count %> reviews </p>
    </div>

     <div class="square-mentor-card-body">
        <img class="square-mentor-card-user" src=<%= mentor.user.pic_url %> alt="mentor-avatar">
        <a class="card-link" href="#" ></a>
        <h2> <%= mentor.minimum_price %> €/hour </h2>
    </div>

    <div class="square-mentor-card-skills">
      <% mentor.tag_names.take(5).each do |skill| %>
        <div class="skill">
          <p><%= skill %></p>
        </div>
      <% end %>
    </div>
  </div>
  <% if @ticket.mentor.blank? %>
    <div class="button">
    <%= simple_form_for @ticket, url: assign_mentor_ticket_path(@ticket), method: :patch do |f| %>
      <%= f.input :mentor_id, as: :hidden, input_html: { value: mentor.user.id } %>
      <%= f.submit "Choose #{mentor.user.first_name} #{mentor.user.last_name}", class: "btn btn-primary text-white ml-2" %>
    <% end %>
    </div>
  <% end %>
</div>

<div class="modal fade" id="myModal<%= mentor.id%>" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
  <div class="modal-dialog modal-lg" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <img class="mentor-card-user" src=<%= mentor.user.pic_url %> alt="mentor-avatar">
        <h4 class="modal-title" id="myModalLabel"><%= mentor.user.first_name %> <%= mentor.user.last_name %></h4>
        <p><%= mentor.user.batch_wagon %></p>
        <% if mentor.user.slack_id %>
          <p>
            <%= link_to "https://lewagon-alumni.slack.com/messages/#{mentor.user.slack_id}/", target: "_blank" do %>
              <%= image_tag'slack-1.svg', :class => "slack_img" %>
            <% end %>
          </p>
        <% end %>
      </div>
      <div class="modal-body">
        <div class="skill"><p><%= mentor.tag_names %></p></div>
        <h4> Experiences </h4>
        <p><%= mentor.experience %></p>
        <h4> Reviews </h4>
        <p><%= render 'shared/reviewscard', reviews: mentor.user.reviews %>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
      </div>
    </div>
  </div>
</div>

app/views/shared/_ticket.html.erb
<div class="d-flex justify-content-center text-white">

      <div class="ticket">
        <form>
          <div class="form-group">
            <label for="subject">What exactly are you trying to accomplish ?</label>
            <input type="text" class="form-control" id="subject" placeholder="Build an app, learn a skill...">
          </div>
          <div class="form-group">
            <label for="description">Why do you need a mentor</label>
            <textarea class="form-control" id="description" placeholder="Create a website, add geolocation to a website..."></textarea>
          </div>
          <div class="input-group mb-3">
            <div class="custom-file">
              <input type="file" class="custom-file-input" id="inputGroupFile01" value="Upload">
              <label class="custom-file-label" for="inputGroupFile01">Any file ?</label>
            </div>
          </div>
          <div class="form-group">
            <label for="inputState">Which languages will you be using</label>
            <select id="inputState" class="form-control">
              <option selected>Languages</option>
              <option>HTML</option>
              <option>CSS</option>
              <option>Javascript</option>
              <option>Ruby</option>
            </select>
          </div>

          <div class = "d-flex justify-content-center flex-column">
            <div class = "d-flex justify-content-center">
              <div class="form-check form-check-inline">
                <input class="form-check-input" type="checkbox" id="inlineCheckbox1" value="option1">
                <label class="form-check-label" for="inlineCheckbox1">HTML</label>
              </div>
              <div class="form-check form-check-inline">
                <input class="form-check-input" type="checkbox" id="inlineCheckbox2" value="option2">
                <label class="form-check-label" for="inlineCheckbox2">CSS</label>
              </div>
              <div class="form-check form-check-inline">
                <input class="form-check-input" type="checkbox" id="inlineCheckbox3" value="option3">
                <label class="form-check-label" for="inlineCheckbox3">Javascript</label>
              </div>
              <div class="form-check form-check-inline">
                <input class="form-check-input" type="checkbox" id="inlineCheckbox4" value="option4">
                <label class="form-check-label" for="inlineCheckbox4">Ruby</label>
              </div>
              <div class="form-check form-check-inline">
                <input class="form-check-input" type="checkbox" id="inlineCheckbox5" value="option5">
                <label class="form-check-label" for="inlineCheckbox5">PHP</label>
              </div>
              <div class="form-check form-check-inline">
                <input class="form-check-input" type="checkbox" id="inlineCheckbox6" value="option6">
                <label class="form-check-label" for="inlineCheckbox6">Others</label>
              </div>
            </div>
            <button type="submit" class="btn btn-secondary mt-3">Send</button>

          </div>
        </form>
      </div>

    </div>