config/routes.rb
Rails.application.routes.draw do
  get 'payments/new'

  get 'orders/show'


  devise_for :users,
    controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }

  root to: 'pages#home'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :tickets do
    resources :reviews, only: [:index, :new, :create]
    member do
      patch :assign_mentor
    end
  end


  resources :mentor_profils do
    resources :reviews, only: [:show, :edit, :index]
  end

  resources :orders, only: [:show, :create] do
    resources :payments, only: [:new, :create]
  end


  get '/dashboard', to: 'tickets#index', as: 'dashboard'
  get '/tickets/:id/mentor/:mid', to: 'tickets#mentor', as: 'tickets_mentor'
  post '/tickets/:id/close', to: 'tickets#close', as: 'close_ticket'
end

app/models/ticket.rb
class Ticket < ApplicationRecord
  PRIORITIES = ["high", "medium", "low"]

  belongs_to :mentor, class_name: 'User', foreign_key: :mentor_id, optional: true
  belongs_to :alumni, class_name: 'User', foreign_key: :alumni_id

  has_one :review, dependent: :destroy
  has_one :mentor_profil, through: :mentor
  has_one :order, dependent: :destroy

  validates :title, :alumni_id, :tag_names, :ticket_duration, :price_cents,  presence: true

  Gutentag::ActiveRecord.call(self)

  monetize :price_cents

  def needs?(skill)
    tag_names.include?(skill)
  end

  def match_mentors
    MentorProfil.tagged_with(
      names: tag_names,
      match: :any
    ).where('minimum_price <= ?', price_cents / 100).order(minimum_price: :asc)
  end
end

app/controllers/tickets_controller.rb
class TicketsController < ApplicationController
  before_action :set_ticket, only: [:show, :edit, :update, :destroy, :mentor, :close, :assign_mentor]

  def index
    @tickets = policy_scope(Ticket)
    #l'instance @selectedstatus sert pour la sélection de l'onglet actif à mettre en rouge
    if params[:status]
      @tickets = Ticket.where(status:params[:status]).order(updated_at: :desc)
      @selectedstatus = params[:status]
    else
      @tickets = Ticket.where(status:params[status: "open"])
      @selectedstatus = "open"
      redirect_to dashboard_path(status: "open")
    end

  end

  def show
    @review = @ticket.review
    @mentor_profils = MentorProfil.all
    match_mentors
    authorize @ticket
  end

  def new
    @ticket = Ticket.new
    authorize @ticket
  end

  def create
    @ticket = Ticket.new(ticket_params)
    @ticket.alumni = current_user
    @ticket.status = "open"
    authorize @ticket
    if @ticket.save
      @ticket.mentor_recommanded_list = match_mentors
      redirect_to dashboard_path(status: "open")
    else
      render :new
    end
  end

  def edit
  end

  def update
    if @ticket.update(ticket_params)
      authorize @ticket
      redirect_to ticket_path(@ticket)
    else
      render :edit
    end
  end

  def destroy
    @ticket.destroy
    redirect_to tickets_path(status: "open"), notice: 'Sniff, Sniff!! Ticket was successfully destroyed.'
  end

  def mentor
    @ticket.mentor = MentorProfil.find(params[:mid]).user
    @ticket.status = "pending"
    authorize @ticket
    @ticket.save
  end

  def close
    @ticket.status = "closed"
    authorize @ticket
    if @ticket.save
      redirect_to ticket_path(@ticket), notice: 'Your Ticket has been successfully closed.'
     end
  end

  def cancel
    @ticket.status = "cancelled"
    authorize @ticket
    @ticket.save
  end

  def assign_mentor
    @mentor = User.find(params[:ticket][:mentor_id])
    @ticket.update(mentor: @mentor)
    order  = Order.create!(ticket_id: @ticket.id, amount: (@ticket.mentor_profil.minimum_price * @ticket.ticket_duration.to_i), state: 'pending')
    redirect_to new_order_payment_path(order), notice: "You've choosen #{@ticket.mentor.mentor_profil.full_name}, the next step is to book hours"
  end

  private

  def set_ticket
    @ticket = Ticket.find(params[:id])
  end

  def ticket_params
    ret = params
      .require(:ticket)
      .permit(
        :content,
        :price,
        :ticket_duration,
        :alumni_id,
        :ticket_location,
        :priority,
        :title,
        :stats,
        :status,
        speaking_language: [],
        tag_names: []
      )
      ret[:speaking_language] = ret[:speaking_language].to_a.reject(&:blank?)
      ret[:tag_names] = ret[:tag_names].to_a.reject(&:blank?)
      ret
  end

  def match_mentors
    @match_mentors_list = @ticket.match_mentors
  end
end

app/views/tickets/_recommanded_mentor.html.erb
<div class="recommanded-mentor general-card">
  <div class="main-mentor-informations">
    <%= image_tag(mentor.pic_url, class: 'avatar-xlarge') %>
    <div class="middle-informations">
      <h3 class="no-margin mentor-full-name"><%= mentor.full_name %></h3>
      <div class="reviews">
        <p class="no-margin secondary-title">
          <% if mentor.reviews.present? %>
            <%= mentor.reviews.count %> <%= "review".pluralize(mentor.reviews.count) %>
          <% else %>
            No review yet
          <% end %>
        </p>
        <% if mentor.reviews.present? %>
          <% 5.times do |i| %>
            <i class="fas fa-star <%= 'active' if mentor.reviews.average(:rating) > i + 1 %>"></i>
          <% end %>
        <% end %>
      </div>
    </div>
    <div class="right-informations">
      <p class="no-margin"><%= mentor.minimum_price %> € / hour<p>
      <% if mentor.user.slack_id %>
        <p>
          <%= link_to "https://lewagon-alumni.slack.com/messages/#{mentor.user.slack_id}/", target: "_blank" do %>
            <%= image_tag'slack-1.svg', :class => "slack_img" %>
          <% end %>
        </p>
      <% end %>
    </div>
  </div>

  <p class="experience"><%= mentor.experience %></p>

  <div class="skills">
    <% mentor.tag_names.each do |skill| %>
      <div class="skill <%= 'match' if @ticket.needs?(skill) %>">
        <p><%= skill %></p>
      </div>
    <% end %>
  </div>

  <ul class="metrics">
    <li>
      <p class="value"><%= mentor.reviews.count %></p>
      <p class="label">tickets mentored</p>
    </li>
    <li>
      <p class="value"><%= mentor.commit_number %></p>
      <p class="label">commits this year</p>
    </li>
    <li>
      <p class="value"><%= mentor.user.batch_wagon %></p>
      <p class="label">Wagon batch number</p>
    </li>
  </ul>

  <ul class="list-inline mentor-actions">
    <li><a class="btn btn-secondary" data-toggle="modal" data-target="#myModal<%= mentor.id%>">View more</a></li>
    <% if @ticket.mentor.blank? %>
      <li>
        <%= simple_form_for @ticket, url: assign_mentor_ticket_path(@ticket), method: :patch do |f| %>
          <%= f.input :mentor_id, as: :hidden, input_html: { value: mentor.user.id } %>
          <%= f.submit "Choose #{mentor.user.first_name} #{mentor.user.last_name}", class: "btn choose-mentor" %>
        <% end %>
      </li>
    <% end %>
  </ul>
</div>

<div class="modal fade" id="myModal<%= mentor.id%>" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
  <div class="modal-dialog modal-lg" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <img class="mentor-card-user" src=<%= mentor.user.pic_url %> alt="mentor-avatar">
        <h4 class="modal-title" id="myModalLabel"><%= mentor.user.first_name %> <%= mentor.user.last_name %></h4>
        <p>Batch <%= mentor.user.batch_wagon %></p>
      </div>
      <div class="modal-body">
        <div class="recommanded-mentor-skills">
          <h4>Mentor skills</h4>
          <% mentor.tag_names.each do |skill| %>
            <div class="skill <%= 'match' if @ticket.needs?(skill) %>">
              <p><%= skill %></p>
            </div>
          <% end %>
        </div>
        <hr>
        <h4> Experiences </h4>
        <p><%= mentor.experience %></p>
        <hr>
        <h4> Reviews </h4>
        <p><%= render 'shared/reviewscard', reviews: mentor.user.reviews %>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
      </div>
    </div>
  </div>
</div>

app/views/tickets/_recommanded_mentors.html.erb
<% if mentors.present? %>
  <div class="row">
    <% mentors.each do |mentor| %>
      <div class="col-xs-12 col-sm-4 col-md-6">
        <%= render 'recommanded_mentor', mentor: mentor %>
      </div>
    <% end %>
  </div>
<% else %>
  <div class="row">
    <div class="col-xs-12">
      <p>No Mentor Found With those skills - Update your Ticket skills or Price</p>
    </div>
  </div>
<% end %>

app/views/tickets/_selected-mentor.html.erb
<div class="selected-mentor general-card">
  <div class="main-mentor-title">
    <%= image_tag(mentor.pic_url, class: 'avatar-xxlarge') %>
    <div class="mentor-full-name">
      <h3><%= mentor.mentor_profil.full_name %></h3>
      <p><i class="fas fa-envelope"></i><%= link_to mentor.email, "mailto:#{mentor.email}" %></p>
      <p><i class="fas fa-phone"></i><%= mentor.phone_number %></p>
      <p><i class="fas fa-hashtag"></i><%= mentor.batch_wagon.gsub('#', 'Batch ') %></p>
    </div>
    <div class="credits">
      <p class="value"><%= @ticket.ticket_duration %></p>
      <p class="title">hours booked</p>
    </div>
 </div>

  <hr>

  <div class="main-mentor-tools">
    <div class="row">
      <div class="col-xs-12 col-sm-8">
        <h4>Working with <%= mentor.first_name.capitalize %></h4>
        <p><%= mentor.first_name.capitalize %> is running a mentor role, so his job is not to make the website or product for you, but only to help you how to start, structure, follow a method, and review what you've done to help you continue learning and gain experience.</p>
        <p>Keep in mind that this project is <strong>your project, your work</strong>, not <%= mentor.first_name.capitalize %> one.</p>
        <p>For asking a question, you should read and follow <a href="https://stackoverflow.com/help/how-to-ask">Stack Overflow guidelines</a> about how to ask a question.
        </p>
    <!--   </div>
    </div>
    <div class="row">
      <div class="col-xs-12 col-sm-8"> -->
        <h4>Tools you can use</h4>
        <ul>
          <li>Communication</li>
          <p>We recommand you to use <%= link_to "https://lewagon-alumni.slack.com/messages/#{mentor.slack_id}/", target: "_blank" do %>
            <%= image_tag 'slack-1.svg', class: 'slack_img' %> Slack (click here to open a private conversation with <%= mentor.first_name.capitalize %>)<% end %>. You can make audio and video calls with slack. This tools are here to help organize communication between team, so don't try to reinvent the wheel, everything can be centralized and archived.</p>
          <li>Coding</li>
          <p>Sometimes, you will need <%= mentor.first_name.capitalize %>'s help on code problems. Good practices for sharing experience from a mentor to an apprentice are both reviewing the code written by the apprentice and pair programming when refactor is needed. We strongly recommand you to interact with <%= mentor.first_name.capitalize %> on those 2 approach. You'll learn a lot !</p>
          <p>You already know the first tool you should use for such a collaboration : <%= link_to 'https://www.github.com', target: '_blank' do %>
            <%= image_tag 'octocat.png', class: 'octocat' %> GitHub
            <% end %>
          </p>
          <p>For distant pair programming sessions, a good tool we recommand is <%= link_to 'https://atom.io/', target: '_blank' do %>
            <%= image_tag 'atom.svg', class: 'atom' %> Atom
            <% end %>with <%= link_to 'https://teletype.atom.io/', target: '_blank' do %>
              Teletype plugin for atom
            <% end %>.
            This plugin will let you work with your mentor on a same file, so usefull for pair programming
          </p>
        </ul>
      </div>
      <div class="col-xs-12 col-sm-4">
        <div class="main-mentor-finish">
          <h4>Mission finished ?</h4>
          <p>When your mission is finished, let us know by closing this ticket and don't forget to leave a review for <%= mentor.first_name.capitalize %></p>
          <div class="ticket_button">
            <% if @ticket.status == "pending" %>
                <% if policy(@ticket).edit? %>
                  <%= link_to 'Complete this mission', close_ticket_path(@ticket),
                  method: :post, data: { confirm: "Are you sure?" }, class: 'btn btn-primary' %>
                <% end %>
            <% elsif @ticket.status == "closed" && @review.blank? %>
              <%= link_to "Add a review for #{mentor.mentor_profil.full_name}", new_ticket_review_path(@ticket), class: "btn-open-s font-20 text-white ml-2",  id: "open_btn"%>
            <% end %>
            <% if @review.present? %>
              <%= @review.rating %>
              <%= @review.description %>
              <%= link_to "back your ticket", dashboard_path %>
            <%end %>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/tickets/create.html.erb
<h1>Tickets#create</h1>

app/views/tickets/destroy.html.erb
<h1>Tickets#destroy</h1>

app/views/tickets/edit.html.erb
<h1>Tickets#edit</h1>
<% if policy(Ticket).create? %>
  <%= render "shared/form", ticket: @ticket %>
<% end %>

app/views/tickets/index.html.erb
<div class="container">
  <div class="main-container">
    <div class="left-panel status-<%= @selectedstatus %>">
      <ul class="sticky-list">
        <div class="status-item tab-open">
          <li class="status-item-text"><%= link_to "OPEN", dashboard_path(status: "open") %></li>
        </div>
        <div class="status-item tab-pending">
          <li class="status-item-text"><%= link_to "PENDING", dashboard_path(status: "pending") %></li>
        </div>
        <div class="status-item tab-closed">
          <li class="status-item-text"><%= link_to "CLOSED", dashboard_path(status: "closed") %></li>
        </div>
        <div class="status-item tab-cancelled">
          <li class="status-item-text"><%= link_to "CANCELLED", dashboard_path(status: "cancelled") %></li>
        </div>
        </ul>
    </div>

    <div class="right-panel">
      <div class="ticket">
        <% if @tickets.present? %>
          <% @tickets.each do |ticket| %>
            <% if policy(ticket).show? %>
              <%= render 'shared/long-ticket-card', ticket: ticket %>
            <% end %>
          <% end %>
        <% else %>
          <div class="row">
            <div class="col-xs-12">
              <div class="blankslate">
                You don't have any <%= params[:status] %> tickets
              </div>
            </div>
          </div>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/tickets/mentor.html.erb
<h1>Selected mentor for your mission</h1>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<div class="card">
  <div class="informations">
    <img src=<%= @ticket.mentor.pic_url %> class="avatar-large" alt="avatar">
    <p><%= @ticket.mentor.first_name %> <%= @ticket.mentor.last_name %></p>
  </div>

  <div class="card-description">
    <% if @ticket.mentor.reviews.blank? %>
      <p>No review yet</p>
    <% else %>
      <ul>
        <% @ticket.mentor.reviews.each do |review| %>
          <li><% review.rating.to_i.times do |i| %>
          <i class="fas fa-star"></i>
        <% end %><% (5 - review.rating.to_i).times do |i| %>
          <i class="far fa-star grey"></i>
        <% end %><%= review.description %> <img src=<%= review.ticket.alumni.pic_url%>  class="avatar-xsmall"></li>
        <% end %>
      </ul>
    <% end %>
    <%= link_to"Add a review for #{@ticket.mentor.first_name}", new_ticket_review_path(@ticket) %>
  </div>
</div>

app/views/tickets/new.html.erb
<% if policy(Ticket).create? %>
  <%= render "shared/form", ticket: @ticket %>
<% end %>

app/views/tickets/show.html.erb
<div class="container">
  <div class="bigticketcard-container">
    <%= render 'shared/bigticketcard', ticket: @ticket %>
  </div>


  <% if @ticket.mentor.blank? %>
    <div class="recommanded-mentors-container">
      <h2><%= @match_mentors_list.count %> mentors are matching your ticket</h2>
      <%= render 'recommanded_mentors', mentors: @match_mentors_list %>
    </div>
  <% else %>
    <div class="selected-mentor-container">
      <h2><%= @ticket.mentor.first_name.capitalize %> will be your mentor for this ticket !</h2>
      <%= render 'selected-mentor', mentor: @ticket.mentor, order: @order %>
    </div>
  <% end %>

app/views/tickets/update.html.erb
<h1>Tags#update</h1>
<p>Find me in app/views/tags/update.html.erb</p>